=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.1
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::AdAudiencesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AdAudiencesApi' do
  before do
    # run before each test
    @api_instance = Late::AdAudiencesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AdAudiencesApi' do
    it 'should create an instance of AdAudiencesApi' do
      expect(@api_instance).to be_instance_of(Late::AdAudiencesApi)
    end
  end

  # unit tests for add_users_to_ad_audience
  # Add users to audience
  # Upload user data (emails and/or phone numbers) to a customer_list audience. Data is SHA256-hashed server-side before sending to Meta. Max 10,000 users per request.
  # @param audience_id 
  # @param add_users_to_ad_audience_request 
  # @param [Hash] opts the optional parameters
  # @return [AddUsersToAdAudience200Response]
  describe 'add_users_to_ad_audience test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_ad_audience
  # Create custom audience
  # Create a customer list, website retargeting, or lookalike audience on Meta (Facebook/Instagram).
  # @param create_ad_audience_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateAdAudience201Response]
  describe 'create_ad_audience test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_ad_audience
  # Delete custom audience
  # Deletes the audience from both Meta and the local database.
  # @param audience_id 
  # @param [Hash] opts the optional parameters
  # @return [DeleteAccountGroup200Response]
  describe 'delete_ad_audience test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_ad_audience
  # Get audience details
  # Returns the local audience record and fresh data from Meta (if available).
  # @param audience_id 
  # @param [Hash] opts the optional parameters
  # @return [GetAdAudience200Response]
  describe 'get_ad_audience test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_ad_audiences
  # List custom audiences
  # Returns custom audiences for the given ad account. Supports Meta, Google, TikTok, and Pinterest.
  # @param account_id Social account ID
  # @param ad_account_id Platform ad account ID
  # @param [Hash] opts the optional parameters
  # @option opts [String] :platform 
  # @return [ListAdAudiences200Response]
  describe 'list_ad_audiences test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
