=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 

The version of the OpenAPI document: 1.91.0
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Zernio::IMessageApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IMessageApi' do
  before do
    # run before each test
    @api_instance = Zernio::IMessageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IMessageApi' do
    it 'should create an instance of IMessageApi' do
      expect(@api_instance).to be_instance_of(Zernio::IMessageApi)
    end
  end

  # unit tests for add_imessage_group_participant
  # Add a participant to an iMessage group
  # Applied asynchronously by the provider; the participant list on the next group webhook reflects it.
  # @param conversation_id 
  # @param add_imessage_group_participant_request 
  # @param [Hash] opts the optional parameters
  # @return [AddImessageGroupParticipant200Response]
  describe 'add_imessage_group_participant test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cancel_imessage_sender
  # Cancel an iMessage sender
  # Cancels the sender at the provider and deactivates its messaging account. Billing stops with the current month (no proration or refunds, matching phone numbers). A sender still being set up (status ordering or activating) cannot be canceled; contact support to change the order. 
  # @param sender_id 
  # @param [Hash] opts the optional parameters
  # @return [OrderImessageSender202Response]
  describe 'cancel_imessage_sender test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_imessage_group
  # Start an iMessage group chat
  # Creates a group chat from one of your senders and sends its first message. The provider processes it asynchronously: the response carries the request id, and the thread appears in the inbox (with its group conversation id) on the first webhook. Starting a group counts as messaging new contacts, so the sender needs the provider&#39;s init-conversations add-on and the same sending intervals apply; without it the request fails with 409 &#x60;recipient_must_message_first&#x60;. WhatsApp groups need a &#x60;name&#x60;. 
  # @param create_imessage_group_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateImessageGroup202Response]
  describe 'create_imessage_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_imessage_opt_in_link
  # Create a tracked iMessage opt-in link
  # Generates a per-campaign link that opens Messages on this sender with &#x60;body&#x60; prefilled. A thread the contact opens skips the pacing and the first-message content rule that apply when the sender writes first, and it is the only way in for senders without the add-on for new contacts (their sends to anyone else fail with &#x60;recipient_must_message_first&#x60;).  Each link carries a unique code in place of the &#x60;[opt-in-code]&#x60; placeholder; when the contact sends it, the resulting &#x60;message.received&#x60; webhook (and the stored inbox message&#39;s &#x60;metadata&#x60;) has &#x60;optIn: true&#x60; and your &#x60;parameters&#x60; under &#x60;optInParameters&#x60;, so you can attribute the conversation to the campaign or lead that produced it.  For an untracked link, use the sender&#39;s &#x60;optInLink&#x60; instead. 
  # @param sender_id 
  # @param create_imessage_opt_in_link_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateImessageOptInLink200Response]
  describe 'create_imessage_opt_in_link test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_imessage_group
  # Get an iMessage group
  # The group&#39;s name, participants and channel as the provider currently sees them. The conversation must be a group thread of the given account.
  # @param conversation_id The inbox conversation id (or the provider group id)
  # @param account_id 
  # @param [Hash] opts the optional parameters
  # @return [GetImessageGroup200Response]
  describe 'get_imessage_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_imessage_sender
  # Get iMessage sender status
  # Lifecycle status of an ordered or registered sender (poll while an order activates), plus the provider&#39;s live platform health for it.
  # @param sender_id 
  # @param [Hash] opts the optional parameters
  # @return [GetImessageSender200Response]
  describe 'get_imessage_sender test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_imessage_audience
  # List iMessage audience
  # Contacts who have messaged your iMessage senders (1:1 threads), with subscription state and, for threads opened through a tracked opt-in link, the parameters that brought them in. Newest activity first.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :account_id Limit to one sender account
  # @option opts [String] :status 
  # @option opts [String] :search Matches the contact handle or name
  # @option opts [Integer] :limit 
  # @option opts [Integer] :skip 
  # @return [ListImessageAudience200Response]
  describe 'list_imessage_audience test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_imessage_available_numbers
  # List instantly available iMessage numbers
  # Phone numbers the provider has already registered and can assign on the spot. Order one by passing its &#x60;id&#x60; as &#x60;availableNumberId&#x60; to POST /v1/imessage/senders/order: the sender activates immediately instead of after the usual provisioning wait. Reserve it first with POST /v1/imessage/senders/available-numbers/{numberId}/reserve while the buyer decides. The list is a snapshot; a number can be taken between listing and ordering. 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :region 
  # @return [ListImessageAvailableNumbers200Response]
  describe 'list_imessage_available_numbers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_imessage_sender_orders
  # List iMessage sender orders
  # Every sender lifecycle doc your team owns (ordered or registered), across statuses. Canceled senders are omitted unless &#x60;includeCanceled&#x3D;true&#x60;.
  # @param [Hash] opts the optional parameters
  # @option opts [Boolean] :include_canceled 
  # @return [ListImessageSenderOrders200Response]
  describe 'list_imessage_sender_orders test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_imessage_senders
  # List iMessage senders
  # Lists the iMessage senders registered across your accessible profiles.
  # @param [Hash] opts the optional parameters
  # @return [ListImessageSenders200Response]
  describe 'list_imessage_senders test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for order_imessage_sender
  # Order a new iMessage sender
  # Orders a NEW dedicated iMessage sender from the delivery provider (compare with POST /v1/imessage/senders, which registers a sender you already own). Activation is asynchronous (minutes to a few hours): the response is 202 with the lifecycle object; poll GET /v1/imessage/senders/{senderId} or subscribe to the account.connected webhook. Billing starts at activation (monthly per sender, no proration). Requires usage-based billing and a valid payment method. Pass purchaseIntentId to make retries idempotent — the provider-side order is never retried automatically. Ordered phone senders include SMS/RCS fallback with call forwarding and the ability to message contacts who have not written first (sending intervals still apply). 
  # @param order_imessage_sender_request 
  # @param [Hash] opts the optional parameters
  # @return [OrderImessageSender202Response]
  describe 'order_imessage_sender test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for register_imessage_sender
  # Register an iMessage sender
  # Registers a provider-provisioned iMessage sender (a phone number or an email handle) that YOU already own on a profile, creating an &#x60;imessage&#x60; account that sends and receives through the inbox conversation endpoints. To have Zernio order a new sender for you, use POST /v1/imessage/senders/order instead. Registration attaches the monthly sender fee (billed while active) and requires a payment method (402 without one). One sender per profile: re-registering the SAME handle refreshes it; a different handle returns 409 until the existing sender is canceled. 
  # @param register_imessage_sender_request 
  # @param [Hash] opts the optional parameters
  # @return [RegisterImessageSender200Response]
  describe 'register_imessage_sender test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_imessage_group_participant
  # Remove a participant from an iMessage group
  # Applied asynchronously by the provider.
  # @param conversation_id 
  # @param account_id 
  # @param contact E.164 phone or iMessage email
  # @param [Hash] opts the optional parameters
  # @return [AddImessageGroupParticipant200Response]
  describe 'remove_imessage_group_participant test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for reserve_imessage_available_number
  # Reserve an available iMessage number
  # Holds the number for 3 minutes so nobody else can order it while the buyer decides. Place the order (POST /v1/imessage/senders/order with availableNumberId) before the hold expires. No request body.
  # @param number_id 
  # @param [Hash] opts the optional parameters
  # @return [ReserveImessageAvailableNumber200Response]
  describe 'reserve_imessage_available_number test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for set_imessage_subscription
  # Subscribe or opt out an iMessage contact
  # Opted-out contacts are refused at send time (409 recipient_opted_out) until re-subscribed. Their inbound messages still arrive. Scoped to your account: it does not change the contact&#39;s state with other businesses.
  # @param set_imessage_subscription_request 
  # @param [Hash] opts the optional parameters
  # @return [SetImessageSubscription200Response]
  describe 'set_imessage_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_imessage_group
  # Rename an iMessage group or change its photo
  # One change per call: either &#x60;name&#x60; or &#x60;photoUrl&#x60; (an empty &#x60;photoUrl&#x60; removes the photo). Applied asynchronously by the provider; a rename is mirrored on the inbox conversation right away.
  # @param conversation_id 
  # @param update_imessage_group_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateImessageGroup200Response]
  describe 'update_imessage_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_imessage_sender
  # Update an iMessage sender
  # Display name (inbox and API responses) and the contact card (vCard) recipients see when they save the sender. The contact card is what a contactCard send shares.
  # @param sender_id 
  # @param update_imessage_sender_request 
  # @param [Hash] opts the optional parameters
  # @return [OrderImessageSender202Response]
  describe 'update_imessage_sender test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
