=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.1
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for Late::SequencesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SequencesApi' do
  before do
    # run before each test
    @api_instance = Late::SequencesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SequencesApi' do
    it 'should create an instance of SequencesApi' do
      expect(@api_instance).to be_instance_of(Late::SequencesApi)
    end
  end

  # unit tests for activate_sequence
  # Activate sequence
  # @param sequence_id 
  # @param [Hash] opts the optional parameters
  # @return [ActivateSequence200Response]
  describe 'activate_sequence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_sequence
  # Create sequence
  # @param create_sequence_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateSequence200Response]
  describe 'create_sequence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_sequence
  # Delete sequence
  # @param sequence_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_sequence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for enroll_contacts
  # Enroll contacts in a sequence
  # @param sequence_id 
  # @param enroll_contacts_request 
  # @param [Hash] opts the optional parameters
  # @return [EnrollContacts200Response]
  describe 'enroll_contacts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_sequence
  # Get sequence with steps
  # @param sequence_id 
  # @param [Hash] opts the optional parameters
  # @return [GetSequence200Response]
  describe 'get_sequence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_sequence_enrollments
  # List enrollments for a sequence
  # @param sequence_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :status 
  # @option opts [Integer] :limit 
  # @option opts [Integer] :skip 
  # @return [ListSequenceEnrollments200Response]
  describe 'list_sequence_enrollments test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_sequences
  # List sequences
  # @param [Hash] opts the optional parameters
  # @option opts [String] :profile_id Filter by profile. Omit to list across all profiles
  # @option opts [String] :status 
  # @option opts [Integer] :limit 
  # @option opts [Integer] :skip 
  # @return [ListSequences200Response]
  describe 'list_sequences test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for pause_sequence
  # Pause sequence
  # @param sequence_id 
  # @param [Hash] opts the optional parameters
  # @return [ActivateSequence200Response]
  describe 'pause_sequence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for unenroll_contact
  # Unenroll contact
  # @param sequence_id 
  # @param contact_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'unenroll_contact test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_sequence
  # Update sequence
  # @param sequence_id 
  # @param [Hash] opts the optional parameters
  # @return [UpdateSequence200Response]
  describe 'update_sequence test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
