=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 

The version of the OpenAPI document: 1.47.0
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Zernio::AdKeywordQuality
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Zernio::AdKeywordQuality do
  #let(:instance) { Zernio::AdKeywordQuality.new }

  describe 'test an instance of AdKeywordQuality' do
    it 'should create an instance of AdKeywordQuality' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Zernio::AdKeywordQuality)
    end
  end

  describe 'test attribute "score"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "expected_ctr"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["BELOW_AVERAGE", "AVERAGE", "ABOVE_AVERAGE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.expected_ctr = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "ad_relevance"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["BELOW_AVERAGE", "AVERAGE", "ABOVE_AVERAGE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.ad_relevance = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "landing_page_experience"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["BELOW_AVERAGE", "AVERAGE", "ABOVE_AVERAGE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.landing_page_experience = value }.not_to raise_error
      # end
    end
  end

end
