=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.1
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Zernio::AdTreeAdSetPromotedObject
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Zernio::AdTreeAdSetPromotedObject do
  #let(:instance) { Zernio::AdTreeAdSetPromotedObject.new }

  describe 'test an instance of AdTreeAdSetPromotedObject' do
    it 'should create an instance of AdTreeAdSetPromotedObject' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Zernio::AdTreeAdSetPromotedObject)
    end
  end

  describe 'test attribute "custom_event_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "pixel_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "page_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
