=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.4
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Zernio::AdjustConversions200ResponseFailuresInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Zernio::AdjustConversions200ResponseFailuresInner do
  #let(:instance) { Zernio::AdjustConversions200ResponseFailuresInner.new }

  describe 'test an instance of AdjustConversions200ResponseFailuresInner' do
    it 'should create an instance of AdjustConversions200ResponseFailuresInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Zernio::AdjustConversions200ResponseFailuresInner)
    end
  end

  describe 'test attribute "adjustment_index"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "code"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
