=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.1
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Zernio::GetGoogleBusinessLocationDetails200ResponseCategories
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Zernio::GetGoogleBusinessLocationDetails200ResponseCategories do
  #let(:instance) { Zernio::GetGoogleBusinessLocationDetails200ResponseCategories.new }

  describe 'test an instance of GetGoogleBusinessLocationDetails200ResponseCategories' do
    it 'should create an instance of GetGoogleBusinessLocationDetails200ResponseCategories' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Zernio::GetGoogleBusinessLocationDetails200ResponseCategories)
    end
  end

  describe 'test attribute "primary_category"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "additional_categories"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
