=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.4
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Zernio::ListCommentAutomationLogs200ResponseMissesSamplesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Zernio::ListCommentAutomationLogs200ResponseMissesSamplesInner do
  #let(:instance) { Zernio::ListCommentAutomationLogs200ResponseMissesSamplesInner.new }

  describe 'test an instance of ListCommentAutomationLogs200ResponseMissesSamplesInner' do
    it 'should create an instance of ListCommentAutomationLogs200ResponseMissesSamplesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Zernio::ListCommentAutomationLogs200ResponseMissesSamplesInner)
    end
  end

  describe 'test attribute "comment_text"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "commenter_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "excluded_by"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "at"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
