=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 

The version of the OpenAPI document: 1.41.0
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Zernio::ListAdsTikTokIdentities200ResponseIdentitiesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Zernio::ListAdsTikTokIdentities200ResponseIdentitiesInner do
  #let(:instance) { Zernio::ListAdsTikTokIdentities200ResponseIdentitiesInner.new }

  describe 'test an instance of ListAdsTikTokIdentities200ResponseIdentitiesInner' do
    it 'should create an instance of ListAdsTikTokIdentities200ResponseIdentitiesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Zernio::ListAdsTikTokIdentities200ResponseIdentitiesInner)
    end
  end

  describe 'test attribute "identity_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "identity_type"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["TT_USER", "BC_AUTH_TT", "CUSTOMIZED_USER"])
      # validator.allowable_values.each do |value|
      #   expect { instance.identity_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "display_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "username"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "profile_image"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "identity_authorized_bc_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
