=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.4
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Zernio::ReviewPhoneNumberKycPacket200ResponseAdvisoriesInner
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Zernio::ReviewPhoneNumberKycPacket200ResponseAdvisoriesInner do
  #let(:instance) { Zernio::ReviewPhoneNumberKycPacket200ResponseAdvisoriesInner.new }

  describe 'test an instance of ReviewPhoneNumberKycPacket200ResponseAdvisoriesInner' do
    it 'should create an instance of ReviewPhoneNumberKycPacket200ResponseAdvisoriesInner' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Zernio::ReviewPhoneNumberKycPacket200ResponseAdvisoriesInner)
    end
  end

  describe 'test attribute "requirement_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "concern"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
