=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.4
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Zernio::SubmitPhoneNumberKycRequestDocumentsInnerOneOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe Zernio::SubmitPhoneNumberKycRequestDocumentsInnerOneOf do
  #let(:instance) { Zernio::SubmitPhoneNumberKycRequestDocumentsInnerOneOf.new }

  describe 'test an instance of SubmitPhoneNumberKycRequestDocumentsInnerOneOf' do
    it 'should create an instance of SubmitPhoneNumberKycRequestDocumentsInnerOneOf' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(Zernio::SubmitPhoneNumberKycRequestDocumentsInnerOneOf)
    end
  end

  describe 'test attribute "requirement_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "filename"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "base64"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
