=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.1
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Zernio
  class BoostPostRequest < ApiModelBase
    # Zernio post ID (provide this or platformPostId)
    attr_accessor :post_id

    # Platform post ID (alternative to postId)
    attr_accessor :platform_post_id

    # Social account ID
    attr_accessor :account_id

    # Platform ad account ID
    attr_accessor :ad_account_id

    attr_accessor :name

    # Available goals vary by platform. Meta (Facebook/Instagram) and TikTok support all 7. LinkedIn supports all except app_promotion. Twitter/X supports engagement, traffic, awareness, video_views, app_promotion. Pinterest and Google Ads support only engagement, traffic, awareness, video_views.
    attr_accessor :goal

    attr_accessor :budget

    attr_accessor :currency

    attr_accessor :schedule

    attr_accessor :targeting

    # Meta bid strategy applied to the ad set. On TikTok, mapped to `bid_type` / `bid_price` / `deep_bid_type` automatically. 
    attr_accessor :bid_strategy

    # Bid cap in WHOLE currency units (USD: 5 = $5.00; JPY: 100 = ¥100). Required when `bidStrategy` is `LOWEST_COST_WITH_BID_CAP` or `COST_CAP`. Backward-compat: providing `bidAmount` without `bidStrategy` is treated as `LOWEST_COST_WITH_BID_CAP`. 
    attr_accessor :bid_amount

    # Minimum ROAS as a decimal multiplier (e.g. 2.0 = 2.0x ROAS). Required when `bidStrategy` is `LOWEST_COST_WITH_MIN_ROAS`. Sent to Meta as `bid_constraints.roas_average_floor` × 10000 (Meta uses fixed-point integers). 
    attr_accessor :roas_average_floor

    attr_accessor :tracking

    # Meta only. Required for housing, employment, credit, or political ads.
    attr_accessor :special_ad_categories

    # TikTok-only. Custom destination URL for the Spark Ad. Without this, TikTok Spark Ads have no clickable destination — required for traffic / conversion objectives. Maps to `landing_page_url` on the creative entry of /v2/ad/create/ (TikTok SDK `AdcreateCreatives.landing_page_url`). Ignored on Meta / LinkedIn / Pinterest / X / Google (those infer the destination from the boosted post). 
    attr_accessor :link_url

    # TikTok-only. Call-to-action button label on the Spark Ad creative (e.g. `LEARN_MORE`, `SHOP_NOW`, `DOWNLOAD_NOW`, `SIGN_UP`, `WATCH_NOW`). Maps to `call_to_action` on the creative entry of /v2/ad/create/. Pass-through — the platform validates the value. See TikTok's \"Enumeration - Call-to-Action\" reference for the full list. 
    attr_accessor :call_to_action

    # TikTok-only. Spark Code (creator's `auth_code`) authorizing cross-creator Spark Ads — the advertiser can boost a video owned by a DIFFERENT TikTok account. Without this, boosts are limited to videos owned by the same account running the ads (same-BC creators only). The creator generates the code in their TikTok app's Promote settings and shares it with the advertiser. Maps to `auth_code` on the creative entry of /v2/ad/create/. 
    attr_accessor :spark_auth_code

    # Name of the legal entity benefiting from the ad. Required by Meta when targeting EU users (DSA Article 26). Not enforced at schema level; enforced server-side when targeting intersects EU member states. 
    attr_accessor :dsa_beneficiary

    # Name of the legal entity paying for the ad. Required by Meta when targeting EU users (DSA Article 26). Note Meta API spelling: dsa_payor (not dsa_payer). 
    attr_accessor :dsa_payor

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'post_id' => :'postId',
        :'platform_post_id' => :'platformPostId',
        :'account_id' => :'accountId',
        :'ad_account_id' => :'adAccountId',
        :'name' => :'name',
        :'goal' => :'goal',
        :'budget' => :'budget',
        :'currency' => :'currency',
        :'schedule' => :'schedule',
        :'targeting' => :'targeting',
        :'bid_strategy' => :'bidStrategy',
        :'bid_amount' => :'bidAmount',
        :'roas_average_floor' => :'roasAverageFloor',
        :'tracking' => :'tracking',
        :'special_ad_categories' => :'specialAdCategories',
        :'link_url' => :'linkUrl',
        :'call_to_action' => :'callToAction',
        :'spark_auth_code' => :'sparkAuthCode',
        :'dsa_beneficiary' => :'dsaBeneficiary',
        :'dsa_payor' => :'dsaPayor'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'post_id' => :'String',
        :'platform_post_id' => :'String',
        :'account_id' => :'String',
        :'ad_account_id' => :'String',
        :'name' => :'String',
        :'goal' => :'String',
        :'budget' => :'BoostPostRequestBudget',
        :'currency' => :'String',
        :'schedule' => :'BoostPostRequestSchedule',
        :'targeting' => :'BoostPostRequestTargeting',
        :'bid_strategy' => :'BidStrategy',
        :'bid_amount' => :'Float',
        :'roas_average_floor' => :'Float',
        :'tracking' => :'BoostPostRequestTracking',
        :'special_ad_categories' => :'Array<String>',
        :'link_url' => :'String',
        :'call_to_action' => :'String',
        :'spark_auth_code' => :'String',
        :'dsa_beneficiary' => :'String',
        :'dsa_payor' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zernio::BoostPostRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zernio::BoostPostRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'post_id')
        self.post_id = attributes[:'post_id']
      end

      if attributes.key?(:'platform_post_id')
        self.platform_post_id = attributes[:'platform_post_id']
      end

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      else
        self.account_id = nil
      end

      if attributes.key?(:'ad_account_id')
        self.ad_account_id = attributes[:'ad_account_id']
      else
        self.ad_account_id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'goal')
        self.goal = attributes[:'goal']
      else
        self.goal = nil
      end

      if attributes.key?(:'budget')
        self.budget = attributes[:'budget']
      else
        self.budget = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'schedule')
        self.schedule = attributes[:'schedule']
      end

      if attributes.key?(:'targeting')
        self.targeting = attributes[:'targeting']
      end

      if attributes.key?(:'bid_strategy')
        self.bid_strategy = attributes[:'bid_strategy']
      end

      if attributes.key?(:'bid_amount')
        self.bid_amount = attributes[:'bid_amount']
      end

      if attributes.key?(:'roas_average_floor')
        self.roas_average_floor = attributes[:'roas_average_floor']
      end

      if attributes.key?(:'tracking')
        self.tracking = attributes[:'tracking']
      end

      if attributes.key?(:'special_ad_categories')
        if (value = attributes[:'special_ad_categories']).is_a?(Array)
          self.special_ad_categories = value
        end
      end

      if attributes.key?(:'link_url')
        self.link_url = attributes[:'link_url']
      end

      if attributes.key?(:'call_to_action')
        self.call_to_action = attributes[:'call_to_action']
      end

      if attributes.key?(:'spark_auth_code')
        self.spark_auth_code = attributes[:'spark_auth_code']
      end

      if attributes.key?(:'dsa_beneficiary')
        self.dsa_beneficiary = attributes[:'dsa_beneficiary']
      end

      if attributes.key?(:'dsa_payor')
        self.dsa_payor = attributes[:'dsa_payor']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @account_id.nil?
        invalid_properties.push('invalid value for "account_id", account_id cannot be nil.')
      end

      if @ad_account_id.nil?
        invalid_properties.push('invalid value for "ad_account_id", ad_account_id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 255
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 255.')
      end

      if @goal.nil?
        invalid_properties.push('invalid value for "goal", goal cannot be nil.')
      end

      if @budget.nil?
        invalid_properties.push('invalid value for "budget", budget cannot be nil.')
      end

      if !@dsa_beneficiary.nil? && @dsa_beneficiary.to_s.length > 100
        invalid_properties.push('invalid value for "dsa_beneficiary", the character length must be smaller than or equal to 100.')
      end

      if !@dsa_payor.nil? && @dsa_payor.to_s.length > 100
        invalid_properties.push('invalid value for "dsa_payor", the character length must be smaller than or equal to 100.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @account_id.nil?
      return false if @ad_account_id.nil?
      return false if @name.nil?
      return false if @name.to_s.length > 255
      return false if @goal.nil?
      goal_validator = EnumAttributeValidator.new('String', ["engagement", "traffic", "awareness", "video_views", "lead_generation", "conversions", "app_promotion"])
      return false unless goal_validator.valid?(@goal)
      return false if @budget.nil?
      return false if !@dsa_beneficiary.nil? && @dsa_beneficiary.to_s.length > 100
      return false if !@dsa_payor.nil? && @dsa_payor.to_s.length > 100
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] account_id Value to be assigned
    def account_id=(account_id)
      if account_id.nil?
        fail ArgumentError, 'account_id cannot be nil'
      end

      @account_id = account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] ad_account_id Value to be assigned
    def ad_account_id=(ad_account_id)
      if ad_account_id.nil?
        fail ArgumentError, 'ad_account_id cannot be nil'
      end

      @ad_account_id = ad_account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 255
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 255.'
      end

      @name = name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] goal Object to be assigned
    def goal=(goal)
      validator = EnumAttributeValidator.new('String', ["engagement", "traffic", "awareness", "video_views", "lead_generation", "conversions", "app_promotion"])
      unless validator.valid?(goal)
        fail ArgumentError, "invalid value for \"goal\", must be one of #{validator.allowable_values}."
      end
      @goal = goal
    end

    # Custom attribute writer method with validation
    # @param [Object] budget Value to be assigned
    def budget=(budget)
      if budget.nil?
        fail ArgumentError, 'budget cannot be nil'
      end

      @budget = budget
    end

    # Custom attribute writer method with validation
    # @param [Object] dsa_beneficiary Value to be assigned
    def dsa_beneficiary=(dsa_beneficiary)
      if dsa_beneficiary.nil?
        fail ArgumentError, 'dsa_beneficiary cannot be nil'
      end

      if dsa_beneficiary.to_s.length > 100
        fail ArgumentError, 'invalid value for "dsa_beneficiary", the character length must be smaller than or equal to 100.'
      end

      @dsa_beneficiary = dsa_beneficiary
    end

    # Custom attribute writer method with validation
    # @param [Object] dsa_payor Value to be assigned
    def dsa_payor=(dsa_payor)
      if dsa_payor.nil?
        fail ArgumentError, 'dsa_payor cannot be nil'
      end

      if dsa_payor.to_s.length > 100
        fail ArgumentError, 'invalid value for "dsa_payor", the character length must be smaller than or equal to 100.'
      end

      @dsa_payor = dsa_payor
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          post_id == o.post_id &&
          platform_post_id == o.platform_post_id &&
          account_id == o.account_id &&
          ad_account_id == o.ad_account_id &&
          name == o.name &&
          goal == o.goal &&
          budget == o.budget &&
          currency == o.currency &&
          schedule == o.schedule &&
          targeting == o.targeting &&
          bid_strategy == o.bid_strategy &&
          bid_amount == o.bid_amount &&
          roas_average_floor == o.roas_average_floor &&
          tracking == o.tracking &&
          special_ad_categories == o.special_ad_categories &&
          link_url == o.link_url &&
          call_to_action == o.call_to_action &&
          spark_auth_code == o.spark_auth_code &&
          dsa_beneficiary == o.dsa_beneficiary &&
          dsa_payor == o.dsa_payor
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [post_id, platform_post_id, account_id, ad_account_id, name, goal, budget, currency, schedule, targeting, bid_strategy, bid_amount, roas_average_floor, tracking, special_ad_categories, link_url, call_to_action, spark_auth_code, dsa_beneficiary, dsa_payor].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
