=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 

The version of the OpenAPI document: 1.0.4
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Zernio
  class CreateHighDemandPeriodRequest < ApiModelBase
    # Zernio SocialAccount id used to resolve the Meta token.
    attr_accessor :account_id

    # Platform campaign id. Exactly one of campaignId / adSetId.
    attr_accessor :campaign_id

    # Platform ad set id. Exactly one of campaignId / adSetId.
    attr_accessor :ad_set_id

    # With ABSOLUTE, a budget in the ad account's currency in WHOLE units (50 = $50.00). With MULTIPLIER, a factor of the existing budget (2 = double it) and NOT a currency amount.
    attr_accessor :budget_value

    attr_accessor :budget_value_type

    # Unix seconds, on a 15-minute boundary (:00, :15, :30, :45).
    attr_accessor :time_start

    # Unix seconds, on a 15-minute boundary and after timeStart.
    attr_accessor :time_end

    attr_accessor :recurrence_type

    # Ad account currency, for the ABSOLUTE minor-unit conversion. Ignored for MULTIPLIER.
    attr_accessor :currency

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_id' => :'accountId',
        :'campaign_id' => :'campaignId',
        :'ad_set_id' => :'adSetId',
        :'budget_value' => :'budgetValue',
        :'budget_value_type' => :'budgetValueType',
        :'time_start' => :'timeStart',
        :'time_end' => :'timeEnd',
        :'recurrence_type' => :'recurrenceType',
        :'currency' => :'currency'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_id' => :'String',
        :'campaign_id' => :'String',
        :'ad_set_id' => :'String',
        :'budget_value' => :'Float',
        :'budget_value_type' => :'String',
        :'time_start' => :'Integer',
        :'time_end' => :'Integer',
        :'recurrence_type' => :'String',
        :'currency' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zernio::CreateHighDemandPeriodRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zernio::CreateHighDemandPeriodRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      else
        self.account_id = nil
      end

      if attributes.key?(:'campaign_id')
        self.campaign_id = attributes[:'campaign_id']
      end

      if attributes.key?(:'ad_set_id')
        self.ad_set_id = attributes[:'ad_set_id']
      end

      if attributes.key?(:'budget_value')
        self.budget_value = attributes[:'budget_value']
      else
        self.budget_value = nil
      end

      if attributes.key?(:'budget_value_type')
        self.budget_value_type = attributes[:'budget_value_type']
      else
        self.budget_value_type = nil
      end

      if attributes.key?(:'time_start')
        self.time_start = attributes[:'time_start']
      else
        self.time_start = nil
      end

      if attributes.key?(:'time_end')
        self.time_end = attributes[:'time_end']
      else
        self.time_end = nil
      end

      if attributes.key?(:'recurrence_type')
        self.recurrence_type = attributes[:'recurrence_type']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @account_id.nil?
        invalid_properties.push('invalid value for "account_id", account_id cannot be nil.')
      end

      if @budget_value.nil?
        invalid_properties.push('invalid value for "budget_value", budget_value cannot be nil.')
      end

      if @budget_value_type.nil?
        invalid_properties.push('invalid value for "budget_value_type", budget_value_type cannot be nil.')
      end

      if @time_start.nil?
        invalid_properties.push('invalid value for "time_start", time_start cannot be nil.')
      end

      if @time_end.nil?
        invalid_properties.push('invalid value for "time_end", time_end cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @account_id.nil?
      return false if @budget_value.nil?
      return false if @budget_value_type.nil?
      budget_value_type_validator = EnumAttributeValidator.new('String', ["ABSOLUTE", "MULTIPLIER"])
      return false unless budget_value_type_validator.valid?(@budget_value_type)
      return false if @time_start.nil?
      return false if @time_end.nil?
      recurrence_type_validator = EnumAttributeValidator.new('String', ["ONE_TIME", "WEEKLY", "MONTHLY"])
      return false unless recurrence_type_validator.valid?(@recurrence_type)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] account_id Value to be assigned
    def account_id=(account_id)
      if account_id.nil?
        fail ArgumentError, 'account_id cannot be nil'
      end

      @account_id = account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] budget_value Value to be assigned
    def budget_value=(budget_value)
      if budget_value.nil?
        fail ArgumentError, 'budget_value cannot be nil'
      end

      @budget_value = budget_value
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] budget_value_type Object to be assigned
    def budget_value_type=(budget_value_type)
      validator = EnumAttributeValidator.new('String', ["ABSOLUTE", "MULTIPLIER"])
      unless validator.valid?(budget_value_type)
        fail ArgumentError, "invalid value for \"budget_value_type\", must be one of #{validator.allowable_values}."
      end
      @budget_value_type = budget_value_type
    end

    # Custom attribute writer method with validation
    # @param [Object] time_start Value to be assigned
    def time_start=(time_start)
      if time_start.nil?
        fail ArgumentError, 'time_start cannot be nil'
      end

      @time_start = time_start
    end

    # Custom attribute writer method with validation
    # @param [Object] time_end Value to be assigned
    def time_end=(time_end)
      if time_end.nil?
        fail ArgumentError, 'time_end cannot be nil'
      end

      @time_end = time_end
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] recurrence_type Object to be assigned
    def recurrence_type=(recurrence_type)
      validator = EnumAttributeValidator.new('String', ["ONE_TIME", "WEEKLY", "MONTHLY"])
      unless validator.valid?(recurrence_type)
        fail ArgumentError, "invalid value for \"recurrence_type\", must be one of #{validator.allowable_values}."
      end
      @recurrence_type = recurrence_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_id == o.account_id &&
          campaign_id == o.campaign_id &&
          ad_set_id == o.ad_set_id &&
          budget_value == o.budget_value &&
          budget_value_type == o.budget_value_type &&
          time_start == o.time_start &&
          time_end == o.time_end &&
          recurrence_type == o.recurrence_type &&
          currency == o.currency
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_id, campaign_id, ad_set_id, budget_value, budget_value_type, time_start, time_end, recurrence_type, currency].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
