=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.4
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Zernio
  class EnableVoiceOnNumber200Response < ApiModelBase
    attr_accessor :enabled

    attr_accessor :phone_number

    attr_accessor :pstn_forward_to

    attr_accessor :recording_enabled

    attr_accessor :transcription_enabled

    attr_accessor :transcription_language

    attr_accessor :voicemail_enabled

    attr_accessor :voicemail_greeting

    attr_accessor :business_hours_enabled

    attr_accessor :business_hours_timezone

    attr_accessor :business_hours

    attr_accessor :blocked_callers

    attr_accessor :forward_caller_id

    attr_accessor :ivr_enabled

    attr_accessor :ivr_prompt

    attr_accessor :ivr_options

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'enabled' => :'enabled',
        :'phone_number' => :'phoneNumber',
        :'pstn_forward_to' => :'pstnForwardTo',
        :'recording_enabled' => :'recordingEnabled',
        :'transcription_enabled' => :'transcriptionEnabled',
        :'transcription_language' => :'transcriptionLanguage',
        :'voicemail_enabled' => :'voicemailEnabled',
        :'voicemail_greeting' => :'voicemailGreeting',
        :'business_hours_enabled' => :'businessHoursEnabled',
        :'business_hours_timezone' => :'businessHoursTimezone',
        :'business_hours' => :'businessHours',
        :'blocked_callers' => :'blockedCallers',
        :'forward_caller_id' => :'forwardCallerId',
        :'ivr_enabled' => :'ivrEnabled',
        :'ivr_prompt' => :'ivrPrompt',
        :'ivr_options' => :'ivrOptions'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'enabled' => :'Boolean',
        :'phone_number' => :'String',
        :'pstn_forward_to' => :'String',
        :'recording_enabled' => :'Boolean',
        :'transcription_enabled' => :'Boolean',
        :'transcription_language' => :'String',
        :'voicemail_enabled' => :'Boolean',
        :'voicemail_greeting' => :'String',
        :'business_hours_enabled' => :'Boolean',
        :'business_hours_timezone' => :'String',
        :'business_hours' => :'Array<EnableVoiceOnNumber200ResponseBusinessHoursInner>',
        :'blocked_callers' => :'Array<String>',
        :'forward_caller_id' => :'String',
        :'ivr_enabled' => :'Boolean',
        :'ivr_prompt' => :'String',
        :'ivr_options' => :'Array<EnableVoiceOnNumber200ResponseIvrOptionsInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'pstn_forward_to',
        :'voicemail_greeting',
        :'business_hours_timezone',
        :'ivr_prompt',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zernio::EnableVoiceOnNumber200Response` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zernio::EnableVoiceOnNumber200Response`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'enabled')
        self.enabled = attributes[:'enabled']
      end

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end

      if attributes.key?(:'pstn_forward_to')
        self.pstn_forward_to = attributes[:'pstn_forward_to']
      end

      if attributes.key?(:'recording_enabled')
        self.recording_enabled = attributes[:'recording_enabled']
      end

      if attributes.key?(:'transcription_enabled')
        self.transcription_enabled = attributes[:'transcription_enabled']
      end

      if attributes.key?(:'transcription_language')
        self.transcription_language = attributes[:'transcription_language']
      end

      if attributes.key?(:'voicemail_enabled')
        self.voicemail_enabled = attributes[:'voicemail_enabled']
      end

      if attributes.key?(:'voicemail_greeting')
        self.voicemail_greeting = attributes[:'voicemail_greeting']
      end

      if attributes.key?(:'business_hours_enabled')
        self.business_hours_enabled = attributes[:'business_hours_enabled']
      end

      if attributes.key?(:'business_hours_timezone')
        self.business_hours_timezone = attributes[:'business_hours_timezone']
      end

      if attributes.key?(:'business_hours')
        if (value = attributes[:'business_hours']).is_a?(Array)
          self.business_hours = value
        end
      end

      if attributes.key?(:'blocked_callers')
        if (value = attributes[:'blocked_callers']).is_a?(Array)
          self.blocked_callers = value
        end
      end

      if attributes.key?(:'forward_caller_id')
        self.forward_caller_id = attributes[:'forward_caller_id']
      end

      if attributes.key?(:'ivr_enabled')
        self.ivr_enabled = attributes[:'ivr_enabled']
      end

      if attributes.key?(:'ivr_prompt')
        self.ivr_prompt = attributes[:'ivr_prompt']
      end

      if attributes.key?(:'ivr_options')
        if (value = attributes[:'ivr_options']).is_a?(Array)
          self.ivr_options = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      transcription_language_validator = EnumAttributeValidator.new('String', ["auto", "en", "es"])
      return false unless transcription_language_validator.valid?(@transcription_language)
      forward_caller_id_validator = EnumAttributeValidator.new('String', ["business", "caller"])
      return false unless forward_caller_id_validator.valid?(@forward_caller_id)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] transcription_language Object to be assigned
    def transcription_language=(transcription_language)
      validator = EnumAttributeValidator.new('String', ["auto", "en", "es"])
      unless validator.valid?(transcription_language)
        fail ArgumentError, "invalid value for \"transcription_language\", must be one of #{validator.allowable_values}."
      end
      @transcription_language = transcription_language
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] forward_caller_id Object to be assigned
    def forward_caller_id=(forward_caller_id)
      validator = EnumAttributeValidator.new('String', ["business", "caller"])
      unless validator.valid?(forward_caller_id)
        fail ArgumentError, "invalid value for \"forward_caller_id\", must be one of #{validator.allowable_values}."
      end
      @forward_caller_id = forward_caller_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          enabled == o.enabled &&
          phone_number == o.phone_number &&
          pstn_forward_to == o.pstn_forward_to &&
          recording_enabled == o.recording_enabled &&
          transcription_enabled == o.transcription_enabled &&
          transcription_language == o.transcription_language &&
          voicemail_enabled == o.voicemail_enabled &&
          voicemail_greeting == o.voicemail_greeting &&
          business_hours_enabled == o.business_hours_enabled &&
          business_hours_timezone == o.business_hours_timezone &&
          business_hours == o.business_hours &&
          blocked_callers == o.blocked_callers &&
          forward_caller_id == o.forward_caller_id &&
          ivr_enabled == o.ivr_enabled &&
          ivr_prompt == o.ivr_prompt &&
          ivr_options == o.ivr_options
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [enabled, phone_number, pstn_forward_to, recording_enabled, transcription_enabled, transcription_language, voicemail_enabled, voicemail_greeting, business_hours_enabled, business_hours_timezone, business_hours, blocked_callers, forward_caller_id, ivr_enabled, ivr_prompt, ivr_options].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
