=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.4
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Zernio
  # Attach a licensed music track or original sound from the Instagram audio catalog to a Reel. Reels only (single video post, not a story or image). Requires an Instagram account connected via Facebook Login; classic Instagram Login accounts get a 400 (instagram_audio_requires_facebook_login). Get audio IDs from GET /v1/accounts/{accountId}/instagram/audio. If the track becomes unavailable by publish time (removed, region-blocked, licensing change), the post fails with a user-error; it is not published without the audio.
  class InstagramPlatformDataAudioConfiguration < ApiModelBase
    # Audio asset ID from the audio search endpoint.
    attr_accessor :audio_id

    # Volume of the attached audio track, 0-100. Defaults to 100.
    attr_accessor :audio_volume

    # Volume of the video's own sound, 0-100. Defaults to 100. Set 0 to mute the original video audio.
    attr_accessor :video_volume

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'audio_id' => :'audioId',
        :'audio_volume' => :'audioVolume',
        :'video_volume' => :'videoVolume'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'audio_id' => :'String',
        :'audio_volume' => :'Integer',
        :'video_volume' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zernio::InstagramPlatformDataAudioConfiguration` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zernio::InstagramPlatformDataAudioConfiguration`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'audio_id')
        self.audio_id = attributes[:'audio_id']
      else
        self.audio_id = nil
      end

      if attributes.key?(:'audio_volume')
        self.audio_volume = attributes[:'audio_volume']
      end

      if attributes.key?(:'video_volume')
        self.video_volume = attributes[:'video_volume']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @audio_id.nil?
        invalid_properties.push('invalid value for "audio_id", audio_id cannot be nil.')
      end

      if !@audio_volume.nil? && @audio_volume > 100
        invalid_properties.push('invalid value for "audio_volume", must be smaller than or equal to 100.')
      end

      if !@audio_volume.nil? && @audio_volume < 0
        invalid_properties.push('invalid value for "audio_volume", must be greater than or equal to 0.')
      end

      if !@video_volume.nil? && @video_volume > 100
        invalid_properties.push('invalid value for "video_volume", must be smaller than or equal to 100.')
      end

      if !@video_volume.nil? && @video_volume < 0
        invalid_properties.push('invalid value for "video_volume", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @audio_id.nil?
      return false if !@audio_volume.nil? && @audio_volume > 100
      return false if !@audio_volume.nil? && @audio_volume < 0
      return false if !@video_volume.nil? && @video_volume > 100
      return false if !@video_volume.nil? && @video_volume < 0
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] audio_id Value to be assigned
    def audio_id=(audio_id)
      if audio_id.nil?
        fail ArgumentError, 'audio_id cannot be nil'
      end

      @audio_id = audio_id
    end

    # Custom attribute writer method with validation
    # @param [Object] audio_volume Value to be assigned
    def audio_volume=(audio_volume)
      if audio_volume.nil?
        fail ArgumentError, 'audio_volume cannot be nil'
      end

      if audio_volume > 100
        fail ArgumentError, 'invalid value for "audio_volume", must be smaller than or equal to 100.'
      end

      if audio_volume < 0
        fail ArgumentError, 'invalid value for "audio_volume", must be greater than or equal to 0.'
      end

      @audio_volume = audio_volume
    end

    # Custom attribute writer method with validation
    # @param [Object] video_volume Value to be assigned
    def video_volume=(video_volume)
      if video_volume.nil?
        fail ArgumentError, 'video_volume cannot be nil'
      end

      if video_volume > 100
        fail ArgumentError, 'invalid value for "video_volume", must be smaller than or equal to 100.'
      end

      if video_volume < 0
        fail ArgumentError, 'invalid value for "video_volume", must be greater than or equal to 0.'
      end

      @video_volume = video_volume
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          audio_id == o.audio_id &&
          audio_volume == o.audio_volume &&
          video_volume == o.video_volume
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [audio_id, audio_volume, video_volume].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
