=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.1
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Zernio
  # Phone number entry. Field names use Meta WhatsApp Cloud API snake_case (passed through unchanged); wabaId and wabaName are Zernio enrichment.
  class ListWhatsAppPhoneNumbers200ResponsePhoneNumbersInner < ApiModelBase
    # Phone Number ID (Meta)
    attr_accessor :id

    # E.164-formatted display number
    attr_accessor :display_phone_number

    # Meta-verified business name
    attr_accessor :verified_name

    # GREEN, YELLOW, RED, or UNKNOWN
    attr_accessor :quality_rating

    # APPROVED, PENDING_REVIEW, DECLINED, or NONE
    attr_accessor :name_status

    # TIER_250, TIER_1K, TIER_10K, TIER_100K, or TIER_UNLIMITED
    attr_accessor :messaging_limit_tier

    # WhatsApp Business Account ID (Zernio enrichment)
    attr_accessor :waba_id

    # WABA display name (Zernio enrichment)
    attr_accessor :waba_name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'display_phone_number' => :'display_phone_number',
        :'verified_name' => :'verified_name',
        :'quality_rating' => :'quality_rating',
        :'name_status' => :'name_status',
        :'messaging_limit_tier' => :'messaging_limit_tier',
        :'waba_id' => :'wabaId',
        :'waba_name' => :'wabaName'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'display_phone_number' => :'String',
        :'verified_name' => :'String',
        :'quality_rating' => :'String',
        :'name_status' => :'String',
        :'messaging_limit_tier' => :'String',
        :'waba_id' => :'String',
        :'waba_name' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zernio::ListWhatsAppPhoneNumbers200ResponsePhoneNumbersInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zernio::ListWhatsAppPhoneNumbers200ResponsePhoneNumbersInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'display_phone_number')
        self.display_phone_number = attributes[:'display_phone_number']
      end

      if attributes.key?(:'verified_name')
        self.verified_name = attributes[:'verified_name']
      end

      if attributes.key?(:'quality_rating')
        self.quality_rating = attributes[:'quality_rating']
      end

      if attributes.key?(:'name_status')
        self.name_status = attributes[:'name_status']
      end

      if attributes.key?(:'messaging_limit_tier')
        self.messaging_limit_tier = attributes[:'messaging_limit_tier']
      end

      if attributes.key?(:'waba_id')
        self.waba_id = attributes[:'waba_id']
      end

      if attributes.key?(:'waba_name')
        self.waba_name = attributes[:'waba_name']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          display_phone_number == o.display_phone_number &&
          verified_name == o.verified_name &&
          quality_rating == o.quality_rating &&
          name_status == o.name_status &&
          messaging_limit_tier == o.messaging_limit_tier &&
          waba_id == o.waba_id &&
          waba_name == o.waba_name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, display_phone_number, verified_name, quality_rating, name_status, messaging_limit_tier, waba_id, waba_name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
