=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 

The version of the OpenAPI document: 1.0.4
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Zernio
  class ListPhoneNumberCountries200ResponseCountriesInner < ApiModelBase
    # ISO 3166-1 alpha-2
    attr_accessor :code

    attr_accessor :tier

    attr_accessor :monthly_cents

    attr_accessor :needs_kyc

    # Regular phone (PSTN) calling on the number, inbound + outbound. Available on every offerable country.
    attr_accessor :calls_available

    # WhatsApp can be enabled on numbers from this country.
    attr_accessor :whatsapp_available

    # Whether this country's number type can do SMS. Use it to filter the picker when the buyer wants SMS (pair with `wantsSms` on purchase).
    attr_accessor :sms_available

    # WhatsApp Business Calling (BIC) outbound availability, a Meta feature blocked in some countries. NOT the PSTN Calls feature (`callsAvailable`).
    attr_accessor :outbound_calling_available

    # Live carrier-stock snapshot (refreshed every 6h + on availability checks): false when NO offered type currently has deliverable inventory, so a purchase would fail. Treat as advisory; the purchase itself re-checks.
    attr_accessor :in_stock

    # Every number type offered in this country (default first). Capabilities, KYC tier, monthly price, and stock are per type. The country-level fields above mirror the first (default) entry. Pass the chosen `numberType` to POST /v1/phone-numbers/purchase. 
    attr_accessor :types

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'code' => :'code',
        :'tier' => :'tier',
        :'monthly_cents' => :'monthlyCents',
        :'needs_kyc' => :'needsKyc',
        :'calls_available' => :'callsAvailable',
        :'whatsapp_available' => :'whatsappAvailable',
        :'sms_available' => :'smsAvailable',
        :'outbound_calling_available' => :'outboundCallingAvailable',
        :'in_stock' => :'inStock',
        :'types' => :'types'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'code' => :'String',
        :'tier' => :'Integer',
        :'monthly_cents' => :'Integer',
        :'needs_kyc' => :'Boolean',
        :'calls_available' => :'Boolean',
        :'whatsapp_available' => :'Boolean',
        :'sms_available' => :'Boolean',
        :'outbound_calling_available' => :'Boolean',
        :'in_stock' => :'Boolean',
        :'types' => :'Array<ListPhoneNumberCountries200ResponseCountriesInnerTypesInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zernio::ListPhoneNumberCountries200ResponseCountriesInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zernio::ListPhoneNumberCountries200ResponseCountriesInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'code')
        self.code = attributes[:'code']
      end

      if attributes.key?(:'tier')
        self.tier = attributes[:'tier']
      end

      if attributes.key?(:'monthly_cents')
        self.monthly_cents = attributes[:'monthly_cents']
      end

      if attributes.key?(:'needs_kyc')
        self.needs_kyc = attributes[:'needs_kyc']
      end

      if attributes.key?(:'calls_available')
        self.calls_available = attributes[:'calls_available']
      end

      if attributes.key?(:'whatsapp_available')
        self.whatsapp_available = attributes[:'whatsapp_available']
      end

      if attributes.key?(:'sms_available')
        self.sms_available = attributes[:'sms_available']
      end

      if attributes.key?(:'outbound_calling_available')
        self.outbound_calling_available = attributes[:'outbound_calling_available']
      end

      if attributes.key?(:'in_stock')
        self.in_stock = attributes[:'in_stock']
      end

      if attributes.key?(:'types')
        if (value = attributes[:'types']).is_a?(Array)
          self.types = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      tier_validator = EnumAttributeValidator.new('Integer', [1, 2, 3, 4])
      return false unless tier_validator.valid?(@tier)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] tier Object to be assigned
    def tier=(tier)
      validator = EnumAttributeValidator.new('Integer', [1, 2, 3, 4])
      unless validator.valid?(tier)
        fail ArgumentError, "invalid value for \"tier\", must be one of #{validator.allowable_values}."
      end
      @tier = tier
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          code == o.code &&
          tier == o.tier &&
          monthly_cents == o.monthly_cents &&
          needs_kyc == o.needs_kyc &&
          calls_available == o.calls_available &&
          whatsapp_available == o.whatsapp_available &&
          sms_available == o.sms_available &&
          outbound_calling_available == o.outbound_calling_available &&
          in_stock == o.in_stock &&
          types == o.types
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [code, tier, monthly_cents, needs_kyc, calls_available, whatsapp_available, sms_available, outbound_calling_available, in_stock, types].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
