=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 

The version of the OpenAPI document: 1.241.1
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Zernio
  # A conversion event tied to a tracking tag (Google conversion action, LinkedIn conversion rule, X web event tag, OpenAI event setting, TikTok pixel event, Meta custom conversion).
  class TrackingTagEvent < ApiModelBase
    # Platform-native event id, the `{eventId}` of the per-event routes.
    attr_accessor :id

    attr_accessor :name

    # Platform event type or category.
    attr_accessor :type

    # The neutral site event this conversion is fired for, when it maps to one.
    attr_accessor :site_event

    # What the site sends to fire this event (Google conversion label, LinkedIn conversion rule id, X `tw-` event id).
    attr_accessor :site_event_id

    attr_accessor :status

    attr_accessor :default_value

    attr_accessor :currency

    attr_accessor :click_window_days

    attr_accessor :view_window_days

    # Fires only on pages whose URL contains this text (case-insensitive).
    attr_accessor :url_contains

    # `defaultValue` is recorded even when the conversion sends its own value.
    attr_accessor :always_use_default_value

    # Primary conversions count toward bidding and the Conversions column; secondary ones are observation only (Google `primary_for_goal`).
    attr_accessor :primary

    # `one` counts at most one conversion per ad interaction (leads), `every` counts each (purchases).
    attr_accessor :counting_type

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'name' => :'name',
        :'type' => :'type',
        :'site_event' => :'siteEvent',
        :'site_event_id' => :'siteEventId',
        :'status' => :'status',
        :'default_value' => :'defaultValue',
        :'currency' => :'currency',
        :'click_window_days' => :'clickWindowDays',
        :'view_window_days' => :'viewWindowDays',
        :'url_contains' => :'urlContains',
        :'always_use_default_value' => :'alwaysUseDefaultValue',
        :'primary' => :'primary',
        :'counting_type' => :'countingType'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'name' => :'String',
        :'type' => :'String',
        :'site_event' => :'String',
        :'site_event_id' => :'String',
        :'status' => :'String',
        :'default_value' => :'Float',
        :'currency' => :'String',
        :'click_window_days' => :'Integer',
        :'view_window_days' => :'Integer',
        :'url_contains' => :'String',
        :'always_use_default_value' => :'Boolean',
        :'primary' => :'Boolean',
        :'counting_type' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zernio::TrackingTagEvent` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zernio::TrackingTagEvent`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'site_event')
        self.site_event = attributes[:'site_event']
      end

      if attributes.key?(:'site_event_id')
        self.site_event_id = attributes[:'site_event_id']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'default_value')
        self.default_value = attributes[:'default_value']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'click_window_days')
        self.click_window_days = attributes[:'click_window_days']
      end

      if attributes.key?(:'view_window_days')
        self.view_window_days = attributes[:'view_window_days']
      end

      if attributes.key?(:'url_contains')
        self.url_contains = attributes[:'url_contains']
      end

      if attributes.key?(:'always_use_default_value')
        self.always_use_default_value = attributes[:'always_use_default_value']
      end

      if attributes.key?(:'primary')
        self.primary = attributes[:'primary']
      end

      if attributes.key?(:'counting_type')
        self.counting_type = attributes[:'counting_type']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @name.nil?
      site_event_validator = EnumAttributeValidator.new('String', ["page_view", "view_content", "add_to_cart", "search", "initiate_checkout", "add_payment_info", "purchase"])
      return false unless site_event_validator.valid?(@site_event)
      counting_type_validator = EnumAttributeValidator.new('String', ["one", "every"])
      return false unless counting_type_validator.valid?(@counting_type)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] site_event Object to be assigned
    def site_event=(site_event)
      validator = EnumAttributeValidator.new('String', ["page_view", "view_content", "add_to_cart", "search", "initiate_checkout", "add_payment_info", "purchase"])
      unless validator.valid?(site_event)
        fail ArgumentError, "invalid value for \"site_event\", must be one of #{validator.allowable_values}."
      end
      @site_event = site_event
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] counting_type Object to be assigned
    def counting_type=(counting_type)
      validator = EnumAttributeValidator.new('String', ["one", "every"])
      unless validator.valid?(counting_type)
        fail ArgumentError, "invalid value for \"counting_type\", must be one of #{validator.allowable_values}."
      end
      @counting_type = counting_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          name == o.name &&
          type == o.type &&
          site_event == o.site_event &&
          site_event_id == o.site_event_id &&
          status == o.status &&
          default_value == o.default_value &&
          currency == o.currency &&
          click_window_days == o.click_window_days &&
          view_window_days == o.view_window_days &&
          url_contains == o.url_contains &&
          always_use_default_value == o.always_use_default_value &&
          primary == o.primary &&
          counting_type == o.counting_type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, name, type, site_event, site_event_id, status, default_value, currency, click_window_days, view_window_days, url_contains, always_use_default_value, primary, counting_type].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
