=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema). 

The version of the OpenAPI document: 1.0.4
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Zernio
  class UpdateGoogleBusinessLocationDetailsRequest < ApiModelBase
    # Required. Comma-separated fields to update (e.g. 'regularHours', 'specialHours', 'profile.description', 'categories', 'serviceItems'). Any valid Google Business Information API updateMask field is supported.
    attr_accessor :update_mask

    attr_accessor :regular_hours

    attr_accessor :special_hours

    attr_accessor :profile

    attr_accessor :website_uri

    attr_accessor :phone_numbers

    attr_accessor :categories

    # Services offered by the business. Use updateMask='serviceItems' to update.
    attr_accessor :service_items

    # Business name. Use updateMask='title'.
    attr_accessor :title

    # External store identifier, unique within the account. Use updateMask='storeCode'.
    attr_accessor :store_code

    # Free-form, internal-only labels for grouping (1-255 characters each). Use updateMask='labels'.
    attr_accessor :labels

    attr_accessor :storefront_address

    attr_accessor :service_area

    attr_accessor :open_info

    # Additional hours for specific services (delivery, drive-through, etc.). Use updateMask='moreHours'.
    attr_accessor :more_hours

    attr_accessor :latlng

    attr_accessor :ad_words_location_extensions

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'update_mask' => :'updateMask',
        :'regular_hours' => :'regularHours',
        :'special_hours' => :'specialHours',
        :'profile' => :'profile',
        :'website_uri' => :'websiteUri',
        :'phone_numbers' => :'phoneNumbers',
        :'categories' => :'categories',
        :'service_items' => :'serviceItems',
        :'title' => :'title',
        :'store_code' => :'storeCode',
        :'labels' => :'labels',
        :'storefront_address' => :'storefrontAddress',
        :'service_area' => :'serviceArea',
        :'open_info' => :'openInfo',
        :'more_hours' => :'moreHours',
        :'latlng' => :'latlng',
        :'ad_words_location_extensions' => :'adWordsLocationExtensions'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'update_mask' => :'String',
        :'regular_hours' => :'UpdateGoogleBusinessLocationDetailsRequestRegularHours',
        :'special_hours' => :'GetGoogleBusinessLocationDetails200ResponseSpecialHours',
        :'profile' => :'UpdateGoogleBusinessLocationDetailsRequestProfile',
        :'website_uri' => :'String',
        :'phone_numbers' => :'GetGoogleBusinessLocationDetails200ResponsePhoneNumbers',
        :'categories' => :'UpdateGoogleBusinessLocationDetailsRequestCategories',
        :'service_items' => :'Array<UpdateGoogleBusinessLocationDetailsRequestServiceItemsInner>',
        :'title' => :'String',
        :'store_code' => :'String',
        :'labels' => :'Array<String>',
        :'storefront_address' => :'UpdateGoogleBusinessLocationDetailsRequestStorefrontAddress',
        :'service_area' => :'UpdateGoogleBusinessLocationDetailsRequestServiceArea',
        :'open_info' => :'UpdateGoogleBusinessLocationDetailsRequestOpenInfo',
        :'more_hours' => :'Array<UpdateGoogleBusinessLocationDetailsRequestMoreHoursInner>',
        :'latlng' => :'UpdateGoogleBusinessLocationDetailsRequestLatlng',
        :'ad_words_location_extensions' => :'UpdateGoogleBusinessLocationDetailsRequestAdWordsLocationExtensions'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zernio::UpdateGoogleBusinessLocationDetailsRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zernio::UpdateGoogleBusinessLocationDetailsRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'update_mask')
        self.update_mask = attributes[:'update_mask']
      else
        self.update_mask = nil
      end

      if attributes.key?(:'regular_hours')
        self.regular_hours = attributes[:'regular_hours']
      end

      if attributes.key?(:'special_hours')
        self.special_hours = attributes[:'special_hours']
      end

      if attributes.key?(:'profile')
        self.profile = attributes[:'profile']
      end

      if attributes.key?(:'website_uri')
        self.website_uri = attributes[:'website_uri']
      end

      if attributes.key?(:'phone_numbers')
        self.phone_numbers = attributes[:'phone_numbers']
      end

      if attributes.key?(:'categories')
        self.categories = attributes[:'categories']
      end

      if attributes.key?(:'service_items')
        if (value = attributes[:'service_items']).is_a?(Array)
          self.service_items = value
        end
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'store_code')
        self.store_code = attributes[:'store_code']
      end

      if attributes.key?(:'labels')
        if (value = attributes[:'labels']).is_a?(Array)
          self.labels = value
        end
      end

      if attributes.key?(:'storefront_address')
        self.storefront_address = attributes[:'storefront_address']
      end

      if attributes.key?(:'service_area')
        self.service_area = attributes[:'service_area']
      end

      if attributes.key?(:'open_info')
        self.open_info = attributes[:'open_info']
      end

      if attributes.key?(:'more_hours')
        if (value = attributes[:'more_hours']).is_a?(Array)
          self.more_hours = value
        end
      end

      if attributes.key?(:'latlng')
        self.latlng = attributes[:'latlng']
      end

      if attributes.key?(:'ad_words_location_extensions')
        self.ad_words_location_extensions = attributes[:'ad_words_location_extensions']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @update_mask.nil?
        invalid_properties.push('invalid value for "update_mask", update_mask cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @update_mask.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] update_mask Value to be assigned
    def update_mask=(update_mask)
      if update_mask.nil?
        fail ArgumentError, 'update_mask cannot be nil'
      end

      @update_mask = update_mask
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          update_mask == o.update_mask &&
          regular_hours == o.regular_hours &&
          special_hours == o.special_hours &&
          profile == o.profile &&
          website_uri == o.website_uri &&
          phone_numbers == o.phone_numbers &&
          categories == o.categories &&
          service_items == o.service_items &&
          title == o.title &&
          store_code == o.store_code &&
          labels == o.labels &&
          storefront_address == o.storefront_address &&
          service_area == o.service_area &&
          open_info == o.open_info &&
          more_hours == o.more_hours &&
          latlng == o.latlng &&
          ad_words_location_extensions == o.ad_words_location_extensions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [update_mask, regular_hours, special_hours, profile, website_uri, phone_numbers, categories, service_items, title, store_code, labels, storefront_address, service_area, open_info, more_hours, latlng, ad_words_location_extensions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
