=begin
#Zernio API

#API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api  Versioning and deprecation: all endpoints are versioned in the URL path (current version: /v1). Breaking changes only ship in a new path version; existing versions keep working. Deprecated operations are marked 'deprecated: true' in this spec and announced in the changelog (https://zernio.com/changelog) before removal.  Errors: every 4xx/5xx response is application/json with a machine-readable 'code' and a human-readable 'error' message (see the ErrorResponse schema).  Request ids: responses carry an X-Request-Id header with the id we log the request under. Quote it when reporting a problem. A valid x-request-id you send is reused as that id. 

The version of the OpenAPI document: 1.170.0
Contact: support@zernio.com
Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module Zernio
  class UpdateCommerceDiscountRequest < ApiModelBase
    attr_accessor :account_id

    attr_accessor :title

    # Required for method code.
    attr_accessor :code

    # For type percentage, e.g. 15 for 15%.
    attr_accessor :percentage

    # For type fixed_amount, a decimal in the store currency.
    attr_accessor :amount

    # fixed_amount only: take the amount off each item instead of once per order.
    attr_accessor :applies_on_each_item

    # Minimum order subtotal, a decimal in the store currency.
    attr_accessor :minimum_subtotal

    attr_accessor :minimum_quantity

    # Code discounts only: total uses allowed.
    attr_accessor :usage_limit

    # Code discounts only.
    attr_accessor :once_per_customer

    # Defaults to now.
    attr_accessor :starts_at

    attr_accessor :ends_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_id' => :'accountId',
        :'title' => :'title',
        :'code' => :'code',
        :'percentage' => :'percentage',
        :'amount' => :'amount',
        :'applies_on_each_item' => :'appliesOnEachItem',
        :'minimum_subtotal' => :'minimumSubtotal',
        :'minimum_quantity' => :'minimumQuantity',
        :'usage_limit' => :'usageLimit',
        :'once_per_customer' => :'oncePerCustomer',
        :'starts_at' => :'startsAt',
        :'ends_at' => :'endsAt'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_id' => :'String',
        :'title' => :'String',
        :'code' => :'String',
        :'percentage' => :'Float',
        :'amount' => :'String',
        :'applies_on_each_item' => :'Boolean',
        :'minimum_subtotal' => :'String',
        :'minimum_quantity' => :'Integer',
        :'usage_limit' => :'Integer',
        :'once_per_customer' => :'Boolean',
        :'starts_at' => :'Time',
        :'ends_at' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'minimum_subtotal',
        :'minimum_quantity',
        :'usage_limit',
        :'ends_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Zernio::UpdateCommerceDiscountRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Zernio::UpdateCommerceDiscountRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      else
        self.account_id = nil
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      end

      if attributes.key?(:'code')
        self.code = attributes[:'code']
      end

      if attributes.key?(:'percentage')
        self.percentage = attributes[:'percentage']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'applies_on_each_item')
        self.applies_on_each_item = attributes[:'applies_on_each_item']
      end

      if attributes.key?(:'minimum_subtotal')
        self.minimum_subtotal = attributes[:'minimum_subtotal']
      end

      if attributes.key?(:'minimum_quantity')
        self.minimum_quantity = attributes[:'minimum_quantity']
      end

      if attributes.key?(:'usage_limit')
        self.usage_limit = attributes[:'usage_limit']
      end

      if attributes.key?(:'once_per_customer')
        self.once_per_customer = attributes[:'once_per_customer']
      end

      if attributes.key?(:'starts_at')
        self.starts_at = attributes[:'starts_at']
      end

      if attributes.key?(:'ends_at')
        self.ends_at = attributes[:'ends_at']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @account_id.nil?
        invalid_properties.push('invalid value for "account_id", account_id cannot be nil.')
      end

      if !@percentage.nil? && @percentage > 100
        invalid_properties.push('invalid value for "percentage", must be smaller than or equal to 100.')
      end

      if !@minimum_quantity.nil? && @minimum_quantity < 1
        invalid_properties.push('invalid value for "minimum_quantity", must be greater than or equal to 1.')
      end

      if !@usage_limit.nil? && @usage_limit < 1
        invalid_properties.push('invalid value for "usage_limit", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @account_id.nil?
      return false if !@percentage.nil? && @percentage > 100
      return false if !@minimum_quantity.nil? && @minimum_quantity < 1
      return false if !@usage_limit.nil? && @usage_limit < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] account_id Value to be assigned
    def account_id=(account_id)
      if account_id.nil?
        fail ArgumentError, 'account_id cannot be nil'
      end

      @account_id = account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] percentage Value to be assigned
    def percentage=(percentage)
      if percentage.nil?
        fail ArgumentError, 'percentage cannot be nil'
      end

      if percentage > 100
        fail ArgumentError, 'invalid value for "percentage", must be smaller than or equal to 100.'
      end

      @percentage = percentage
    end

    # Custom attribute writer method with validation
    # @param [Object] minimum_quantity Value to be assigned
    def minimum_quantity=(minimum_quantity)
      if !minimum_quantity.nil? && minimum_quantity < 1
        fail ArgumentError, 'invalid value for "minimum_quantity", must be greater than or equal to 1.'
      end

      @minimum_quantity = minimum_quantity
    end

    # Custom attribute writer method with validation
    # @param [Object] usage_limit Value to be assigned
    def usage_limit=(usage_limit)
      if !usage_limit.nil? && usage_limit < 1
        fail ArgumentError, 'invalid value for "usage_limit", must be greater than or equal to 1.'
      end

      @usage_limit = usage_limit
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_id == o.account_id &&
          title == o.title &&
          code == o.code &&
          percentage == o.percentage &&
          amount == o.amount &&
          applies_on_each_item == o.applies_on_each_item &&
          minimum_subtotal == o.minimum_subtotal &&
          minimum_quantity == o.minimum_quantity &&
          usage_limit == o.usage_limit &&
          once_per_customer == o.once_per_customer &&
          starts_at == o.starts_at &&
          ends_at == o.ends_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_id, title, code, percentage, amount, applies_on_each_item, minimum_subtotal, minimum_quantity, usage_limit, once_per_customer, starts_at, ends_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
